### ISSUE TITLE
Cache error?

### ISSUE THREAD

**Issue by IvyUK** [drdanio/eve-simple-esi#6]
I keep getting assorted errors such as this, the only way to resolve is to delete cache.* and re-run, am i doing something wrong ?

```
Traceback (most recent call last):
  File "C:\Python\Python39\lib\shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: '92a01377e088xxxxxxxxxxx012244d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\source\evemd\market.py", line 75, in <module>
    data2=ESI.op('/markets/structures/{structure_id}/',params={'structure_id':structure}) #,'type_id':12068 }) 
  File "C:\Python\Python39\lib\site-packages\eve_simple_esi\__init__.py", line 1102, in op
    result=self.get_all_pages(first,pages_count,command,params,method,body) # Getting data
  File "C:\Python\Python39\lib\site-packages\eve_simple_esi\__init__.py", line 842, in get_all_pages
    page=self.op_single(command,params=page_params,method=method,body=body, raw=True, validate_array=validate_array)
  File "C:\Python\Python39\lib\site-packages\eve_simple_esi\__init__.py", line 778, in op_single
    result=self.send_cached_data(uri, body=body, etag=etag, method=method, validate_array=validate_array)
  File "C:\Python\Python39\lib\site-packages\eve_simple_esi\__init__.py", line 500, in send_cached_data
    uri_cache=self.cache.Get(uri_hash)
  File "C:\Python\Python39\lib\site-packages\eve_simple_esi\__init__.py", line 27, in Get
    return self.db[key]
  File "C:\Python\Python39\lib\shelve.py", line 114, in __getitem__
    value = Unpickler(f).load()
_pickle.UnpicklingError: pickle data was truncated
```

**Comment by drdanio** [comment]
Hmm, looks like shelve has key name limit...

You can try to use another databse for cache (not shelve)
It is key-value db.

Db Wrapper code for shelve is:

`class ESICacheServer:
	def __init__(self,file_name='cache.db'):
		self.db_file=file_name
		self.db=shelve.open(self.db_file)

	def Get(self,key):
		if key in self.db:
			return self.db[key]
		return None

	def Del(self,key):
		del self.db[key]

	def Set(self,key,data):
		self.db[key]=data

	def Clear(self,force=False):
		if force:
			self.db.close()
			exts=['bak','dat','dir']
			for ext in exts:
				os.remove(self.db_file+"."+ext)
			self.db=shelve.open(self.db_file)
		else:
			self.db.clear()

	def Close(self):
		self.db.close()

	def Sync(self):
		self.db.sync()`
		
and then you can replcae cache engine with parameter 'callback_cache_server':
`
import eve_simple_esi as esi
...
ESI=esi.ESI(settings,callback_cache_server=my_cache_class)
`
