### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by 1josh13** [drdanio/eve-simple-esi#7]
Hello, 

I am writing a new python app for myself and I am trying to test this locally with a python terminal. I import the following 

```
import requests
from bs4 import BeautifulSoup
import json
import re
import eve_simple_esi as esi

settings={
 	'client_id':"#########################", # go to https://developers.eveonline.com/ create app and get Client ID
 	'client_secret':"'#########################",  # go to https://developers.eveonline.com/ create app and get Secret Key
 	'client_callback_url':"http://localhost:8635/", # default http://localhost:8635/ need to be same as in your app in https://developers.eveonline.com/
 	'user_agent':"#########################",
 	'scopes':[
        'publicData', 'esi-characters.read_contacts.v1', 'esi-characters.write_contacts.v1', 
        'esi-contracts.read_character_contracts.v1', 'esi-corporations.read_contacts.v1'
            ], # ['publicData','esi-location.read_location.v1',...etc.]
 	'port':8635, # default 8635
 }

ESI=esi.ESI(settings)
```

Which works, I then execute: 
```ESI.auth()```

I get the URL, login with my character, and get the `code=#########################` I copy the portion after = 

I then get the following error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\.venv\lib\site-packages\eve_simple_esi\__init__.py", line 607, in auth
    return self.auth_part2()
  File "\.venv\lib\site-packages\eve_simple_esi\__init__.py", line 633, in auth_part2
    sso_auth_response = self.send_token_request(form_values)
  File "\.venv\lib\site-packages\eve_simple_esi\__init__.py", line 395, in send_token_request
    res.raise_for_status()
  File "\.venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://login.eveonline.com/v2/oauth/token
```

**Comment by drdanio** [comment]
Thanks!
works with this.
now i fix authorization error for cli part (where jwt raise Invalid audience error)
